"""ajout brand et categorie a produit

Revision ID: 3f995b3c419e
Revises: 017084e03436
Create Date: 2025-01-23 14:35:55.634910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f995b3c419e'
down_revision = '017084e03436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('categories', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('categories')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
