"""Add barcode to Product

Revision ID: 7f916b3844ae
Revises: 4e9e0270f495
Create Date: 2025-01-22 09:18:31.681300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f916b3844ae'
down_revision = '4e9e0270f495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###
