"""Add barcode et name_eng to Product

Revision ID: 84285127254f
Revises: 7f916b3844ae
Create Date: 2025-01-22 14:06:06.515577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84285127254f'
down_revision = '7f916b3844ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_eng', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('name_fr', sa.String(length=255), nullable=False))
        batch_op.alter_column('img_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('barcode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('barcode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('img_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('name_fr')
        batch_op.drop_column('name_eng')

    # ### end Alembic commands ###
