"""Add barcode et image to Product

Revision ID: db906cb55356
Revises: 7f916b3844ae
Create Date: 2025-01-22 12:26:54.596028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db906cb55356'
down_revision = '7f916b3844ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('barcode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('img_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('barcode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
