version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-container
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysql
      MYSQL_PORT: 3308
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql-data:
